### ISSUE TITLE
Feature request: pascal case and multiple cases

### ISSUE THREAD

**Issue by divmgl** [DukeLuo/eslint-plugin-check-file#13]
We use `PascalCase.tsx` for components in our React projects. We also use `camelCase` for hooks.

Would be nice to be able to enforce this:

``` json
{
  "**/*.{jsx,tsx}": ["PASCAL_CASE", "CAMEL_CASE"]
}
```

Thanks!

**Comment by DukeLuo** [comment]
@divmgl You can do this in one of two ways:
- Target your different types of files, and give them their own naming pattern.
- Write your own naming expression which can match both PASCAL_CASE and CAMEL_CASE.
