### ISSUE TITLE
CAMEL_CASE matching pattern exception case

### ISSUE THREAD

**Issue by yfhui** [DukeLuo/eslint-plugin-check-file#14]
**Describe the bug**
For file name like `g2tClass`, current CAMEL_CASE that cannot support very well

**Expected behavior**
Current if the 2nd char of the file is a number, then no matter what pattern it is, it cannot be recongized as CAMEL_CASE.
I have tried `g2tClass.js` `g2TClass.js` and `G2TClass.js`, all of them failed the CAMCL_CASE, and I expect either `g2tClass.js` `g2TClass.js`  can pass the case

**Plugin configuration**
        "check-file/filename-naming-convention": ["error", {
            "**/classes/**": "CAMEL_CASE",
        }],

**Project structure**
If applicable, add a minimal reproducible project structure generated by the `tree` cmd like the one below.

```sh
.
├── create_folder_file.sh
├── classes
│   ├── classes
│   └── g2tClass.js
├── package-lock.json
├── package.json
└── src
    └── kebab-case
        └── index.js
```

**Desktop (please complete the following information):**
Linux

**Additional context**
Correct me if this is my mistake

**Comment by yfhui** [comment]
I checked the source code and the pattern for CAMEL_CASE is `+([a-z])*([A-Z]*([a-z0-9]))`, seems it's behvaior matches with my observation. If the 2nd character is a number, then it will failed the case

**Comment by DukeLuo** [comment]
@yfhui Thanks for your issue. Your guess is correct, the current pattern of CAMEL_CASE only allow the first word made from a-z. I also agree with `g2tClass` is a valid camelCase style expression, I will release a new version to fix this bug.

**Comment by yfhui** [comment]
thx a lot for your quick response! looking forward for the fix!

**Comment by DukeLuo** [comment]
@yfhui The new version 1.3.1 is released, you can try it now.

**Comment by yfhui** [comment]
solved!
