### ISSUE TITLE
It doesn't seem to check for vue related items, similar to index.vue

### ISSUE THREAD

**Issue by laterdayi** [DukeLuo/eslint-plugin-check-file#15]
It doesn't seem to check for vue related items, similar to index.vue

**Comment by DukeLuo** [comment]
This plugin only works on the files which are specified by the config. Can you provide your config for `check-file` plugin?

**Comment by laterdayi** [comment]
Whether vue related files can be configured

**Comment by DukeLuo** [comment]
Yes, of course. But first of all, you need to config your eslint correctly to make it can work with `.vue` file. You can refer to this: [https://github.com/DukeLuo/wai/blob/main/.eslintrc](https://github.com/DukeLuo/wai/blob/main/.eslintrc)
