### ISSUE TITLE
Unable to lint .png extension 

### ISSUE THREAD

**Issue by savanakbari** [DukeLuo/eslint-plugin-check-file#19]
**Describe the bug**
Plugin does not work on file extension such as `.png` and `.jpg`.  (Though they do not really fall under eslint scope, wanted to check if they are supported)

**Expected behavior**

Below command is not able catch error in the `images` folder whose `.png` are not in `KEBAB_CASE`. Refer the folder code structure.  I have also tried keeping only one rule but it fails too. But if you specify hardcoded full path to image file, lint is able to catch error. (For ex. `"images/folder/imageCamelCase.png": "KEBAB_CASE"` will work)
```
    "check-file/filename-naming-convention": [
      "error",
      {
        "*.{png}":"KEBAB_CASE", 
        "images/**/*.png": "KEBAB_CASE"
      }
    ],
```

**Plugin configuration**
- Posted above. 

**Project structure**

```sh
.
├── create_folder_file.sh
├── kebab-case
│   ├── images
│   │   ├── folder1
│   │     └── imageCamelCase.png
│   │   ├── folder2
│   │      └── image-Some_case.png
│   └── index.js
├── package-lock.json
├── .eslintrc.cjs
├── package.json
 ── index.js
```

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Trying to lint the .png extension and ensuring all are named in KEBAB_CASE.

**Comment by DukeLuo** [comment]
Hi, I've tried your case on my side, and eslint works well with image files. Your lint script might be missing something.

--- ---
My folder structure:
```
├── create_folder_file.sh
├── images
│   ├── folder1
│   │   └── imageCamelCase.png
│   └── folder2
│       ├── image-Some_case.png
│       └── image-kebab.png
├── package-lock.json
└── package.json
```

My .eslintrc file:
```
{
  "plugins": [
    "check-file"
  ],
  "rules": {
    "check-file/filename-naming-convention": [
      "error",
      {
        "images/**/*.png": "KEBAB_CASE"
      }
    ]
  }
}
```

My package.json file:
```
{
  "name": "check-files-sandbox",
  "scripts": {
    "lint": "eslint \"**/*.{ts,tsx,js,png}\""
  },
  "devDependencies": {
    "eslint": "8.19.0",
    "eslint-plugin-check-file": "^2.2.0"
  }
}

```

**Comment by savanakbari** [comment]
Thanks for the prompt reply. I kept getting this below error. I'll try with a fresh project and will close this issue. 

> Parsing error: Unexpected character '�'

**Comment by DukeLuo** [comment]
Maybe I know what happened. Yesterday, I renamed a blank file to .png, so that ESlint would be able to parse it correctly. I used a real .png file today, and I also got this parse error. This makes sense. ESLint is a tool designed for analyzing and checking JavaScript code for syntax and stylistic errors. It is not designed to parse or process binary image files like PNG or JPEG files.

**Comment by geiregjo** [comment]
I just found this ticket. Now I understand all the parsing errors I have on non JS related files. I understand your point but ESLint is being used for all kinds of languages. Also, why would it have to parse the file for the plugin to validate the rules? I don't understand why the filename is not enough?

Can you elaborate? Is there a workaround to have support for files like: svg, ico, png, ...

**Comment by dukeluo** [comment]
With the processor `eslint-processor-check-file` introduced in eslint-plugin-check-file v3, you can now lint non-JS/TS files like images, styles, etc.
