### ISSUE TITLE
Glob exclusion on non-root level does not apply recursively to all sub-folders

### ISSUE THREAD

**Issue by mleimer** [DukeLuo/eslint-plugin-check-file#21]
**Describe the bug**
Given a config like

```
		'check-file/folder-naming-convention': [
			'error',
			{
				'src/pages/**': 'KEBAB_CASE'',
				'src/!(pages)/**': 'CAMEL_CASE',
			}
               ]
```

Then the following folder-names are considered valid:

- `src/pages/first-page/**`
- `src/components/visual/interactiveButton/**`
- `src/components/visual/interactive-button/**`

**Expected behavior**
- `src/components/visual/interactive-button/**` should not be valid, because `interactive-button`is violating the CAMEL_CASE rule.

**Project structure**
```sh
.
└── src
    └── components
        └── visual
            └── interactive-button // should fail here!
                 └── SomeFile.tsx
            └── interactiveButton // should be the only valid format
                 └── SomeFile.tsx
    └── pages
        └── first-page
            └── page.tsx
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04

**Additional information**
This bug only exist if the exclusion is applied on a sub-folder. It doesn't exist if the root-folder (here `src`) is excluded.

**Comment by DukeLuo** [comment]
Thanks for your issue. It seems there is a bug when using with the `!` matcher. I will work on fixing this bug. 

And you can use the following configuration as a workaround, it works well with your test data. 
```json
{
  "plugins": [
    "check-file"
  ],
  "rules": {
    "check-file/folder-naming-convention": [
      "error",
      {
        "src/pages/**/": "KEBAB_CASE",
        "src/components/**/": "CAMEL_CASE"
      }
    ]
  }
}
```

**Comment by DukeLuo** [comment]
@mleimer The new version 2.3.0 is released, you can try it now.
