### ISSUE TITLE
[Bug] `check-file/no-index` doesn't check e.g. `index.config.ts`

### ISSUE THREAD

**Issue by wenfangdu** [DukeLuo/eslint-plugin-check-file#26]
With `'check-file/no-index': 'error'`, `index.config.ts` is allowed.

**Comment by DukeLuo** [comment]
@wenfangdu Thanks for your issue. The rule`no-index` doesn't support ignore middle file extensions like the rule `filename-naming-convention` currently. It will just disallow the file which name is strict equal `index`. 

I would consider adding `ignoreMiddleExtensions` support for `no-index` rule.
