### ISSUE TITLE
How to support the configuration of multiple matching rules

### ISSUE THREAD

**Issue by iceycc** [DukeLuo/eslint-plugin-check-file#28]
**Project structure**
I would like to support both canonical configurations. as follows:

```sh
└── src
    └── kebabCase.js
    └── kebab-case.js
```

Whether the following configurations are supported： 
```json
 "src/**/!(App).vue": "KEBAB_CASE|PASCAL_CASE",
```

**Comment by MixMasterMitch** [comment]
Could you take this as a feature request?

I have decided not to use this package specifically because it does not support this feature.

**Comment by DukeLuo** [comment]
It's actually quite simple to create your own glob pattern to combine the built in naming pattern. Here's a step-by-step guide to help you out:
1. First, head over to the [file](https://github.com/DukeLuo/eslint-plugin-check-file/blob/main/lib/constants/naming-convention.js) where the built-in naming patterns are defined. You'll find the `KEBAB_CASE` pattern as `+([a-z])*([a-z0-9])*(-+([a-z0-9]))`, and the `PASCAL_CASE` pattern as `*([A-Z]*([a-z0-9]))`.
2. To combine `KEBAB_CASE` and `PASCAL_CASE`, use the `@(pattern1 | pattern2)` syntax. In this case, the combined pattern will look like this: `@(+([a-z])*([a-z0-9])*(-+([a-z0-9])) | *([A-Z]*([a-z0-9])))`.
3. Go to the website [globster.xyz](https://globster.xyz/) and verify your combined pattern.
4. Once you are satisfied with the combined pattern, you can copy and integrate it into your `.eslintrc.json` configuration file.
