### ISSUE TITLE
SubFolder name depending on ParentFolder name

### ISSUE THREAD

**Issue by MihaiTrinca** [dukeluo/eslint-plugin-check-file#32]
Hey. Thank you for this plugin ! 

Is it possible to have a naming convention rule for Folders, that takes into account the parent folder name ?
I know it's possible to enforce fileNames to contain the name of the parentFolder. But is it possbile for folders ?
Eg.  something like :

```    "src/folder/*/*": "<1>" ``` 

With a structure like :
```sh

└── src
    └── folder
        └── sub-folder
             └── sub-folder.sub-sub-foldername
```

Also. the final rule should match folders with 'parentFolderName.kebab-case' . So a combination between parentFolder name and kebab-case afterwards

**Comment by dukeluo** [comment]
Hi @MihaiTrinca, thanks for your input. As this seems to be an uncommon use case, I don't think it fits the project's focus. We're aiming for features with broader appeal.
