### ISSUE TITLE
'KEBAB_CASE' fails on dot notation

### ISSUE THREAD

**Issue by joseph-ravenwolfe** [dukeluo/eslint-plugin-check-file#33]
When using `KEBAB_CASE` filename convention. It is not uncommon to use the `.test.js` file extension as a filename convention for tests. 

```
 └── src
     └── my-module.js
 └── tests
     └── my-module.test.js
```

However, this causes the `KEBAB_CASE` filename enforcement to fail for `{ "**/*.js": "KEBAB_CASE" }` This can currently be worked around with a custom Regex, however, I wanted to bring attention to this.

Is this desired behavior?

**Comment by dukeluo** [comment]
@joseph-ravenwolfe `ignoreMiddleExtensions` is all you need. 

https://github.com/dukeluo/eslint-plugin-check-file/blob/main/docs/rules/filename-naming-convention.md#ignoremiddleextensions

**Comment by turker0** [comment]
Hi @dukeluo Can we have this option for `check-file/folder-naming-convention` also

**Comment by dukeluo** [comment]
@turker0 could you share a scenario and give me an example?

**Comment by dukeluo** [comment]
@turker0 This configs works well in my local.

```
├── create_folder_file.sh
├── index.js
├── marketplace.module
│   └── aB
│       └── b-c
│           └── a.js
├── package-lock.json
└── package.json
```

```json
{
  "plugins": ["check-file"],
  "rules": {
    "check-file/folder-naming-convention": [
      "error",
      {
        "marketplace.module/**/": "CAMEL_CASE"
      }
    ]
  }
}
```

```
❯ npm run lint

> lint
> eslint "**/*.{ts,tsx,js,jsx,md}"

marketplace.module/aB/b-c/a.js
  1:1  error  The folder "b-c" does not match the "CAMEL_CASE" pattern  check-file/folder-naming-convention
```

**Comment by turker0** [comment]
@dukeluo right but i can not pass ` gnoreMiddleExtensions: true` to `check-file/folder-naming-convention`

**Comment by dukeluo** [comment]
@turker0 I mean we don't need this new param `gnoreMiddleExtensions: true` in this case since rule `folder-naming-convention` already works.
