### ISSUE TITLE
The new update still requires glob patterns to be matched regardelss of if they are used

### ISSUE THREAD

**Issue by AtlasTom** [dukeluo/eslint-plugin-check-file#36]
**Describe the bug**
The new pattern:
```
module.exports = {
  plugins: ['check-file'],
  rules: {
    'check-file/filename-blocklist': [
      'error',
      { '*.models.ts': '*.model.ts' },
      {
        errorMessage:
          'The file "{{ target }}" is blocked since it since it matches the blocklisted pattern "{{ pattern }}", see contribute.md for details',
      },
    ],
  },
};
```
still requires an expected Glob `{ '*.models.ts': '*.model.ts' },` despite the errorMessage Not using it at all. In addition the previous PR where a non-glob string could be used in the value `{'*models.ts`: `reson models is not allowed`}` also allowed a different reason for each block. The current implementation should at least allow an empty string in value when errorMessage is defined.
It just doesn't make sense to still have to provide a suggested Glob pattern that must pass a glob matching pattern, when it isn't used at all.

**Expected behavior**
```
module.exports = {
  plugins: ['check-file'],
  rules: {
    'check-file/filename-blocklist': [
      'error',
      { '*.models.ts':  'The file "{{ target }}" is blocked since it since it matches the blocklisted pattern "{{ pattern }}", see contribute.md for details'
       '*.otherthing.ts':  'The file "{{ target }}" is blocked since it since it matches the blocklisted pattern "{{ pattern }}", see aDifferent.md for details'
      },
      {
        errorMessage: true 
        },
    ],
  },
};
```
should work and not return the error " 1:1  error  There is an invalid pattern "The file "{{ target }}" is blocked since it since it matches the blocklisted pattern", please double-check it and try again  check-file/filename-blocklist"

OR  at least: 

```
module.exports = {
  plugins: ['check-file'],
  rules: {
    'check-file/filename-blocklist': [
      'error',
      { '*.models.ts': '' },
      {
        errorMessage:
          'The file "{{ target }}" is blocked since it since it matches the blocklisted pattern "{{ pattern }}", see contribute.md for details',
      },
    ],
  },
};
```
should work and not return the error " 1:1  error  There is an invalid pattern "The file "{{ target }}" is blocked since it since it matches the blocklisted pattern", please double-check it and try again  check-file/filename-blocklist"

**Desktop (please complete the following information):**
 - OS:  macOS

**Additional context**

**Comment by dukeluo** [comment]
@AtlasTom Thank you for pointing out this mistake. I appreciate your input. I have decided to go with this solution to address the concerns about the unused suggested glob pattern when using the `errorMessage` parameter. I will be releasing a hotfix to resolve this issue.

```js
module.exports = {
  plugins: ['check-file'],
  rules: {
    'check-file/filename-blocklist': [
      'error',
      { '*.models.ts': '' },
      {
        errorMessage:
          'The file "{{ target }}" is blocked since it matches the blocklisted pattern "{{ pattern }}". Please refer to contribute.md for more details.',
      },
    ],
  },
};
```
The reason I prefer this solution is that there is another rule that also needs to support the `errorMessage` parameter. Additionally, the value of the rule configuration object must follow a specific naming convention string; it cannot be a custom error message string. I believe it is not a good practice to have two different designs for the same feature, so the `errorMessage` should be a string rather than a boolean value.

```js
module.exports = {
  plugins: ['check-file'],
  rules: {
    'check-file/filename-naming-convention': [
      'error',
      { '**/*.{jsx,tsx}': 'CAMEL_CASE', },
      {
        errorMessage:
          'The file "{{ target }}" does not match the file naming convention defined ("{{ pattern }}") for this project. Please see contribute.md for more details.',
      },
    ],
  },
};
```

**Comment by dukeluo** [comment]
@AtlasTom The hotfix v2.7.1 has been released. Would you be able to check if this issue has been resolved with this hotfix?
