### ISSUE TITLE
Glob to exclude __tests__ folder is not working as expected

### ISSUE THREAD

**Issue by saulo-okada-zs** [dukeluo/eslint-plugin-check-file#38]
**Describe the bug**
I'm currently working in a monorepo and want to enforce the Kebab Case convention for my `domains` folder but exclude all the `__tests__` folders inside it.
I've tried to use the expression described in the documentation but it does not work as expected on my project.
If I use the full path, it works as expected. But if I change the intermediate folders for `/**/`, then it doesn't work.

**Expected behavior**
Files inside the `__tests__` should not throw `check-file/folder-naming-convention` error

**Plugin configuration**
```
[.eslintrc.base.json]
...
    "check-file/folder-naming-convention": [
      "error",
      {
        "domains/**/!(__tests__)/**": "KEBAB_CASE", // this doesn't work
        "domains/sub-domain-a/src/!(__tests__)/**": "KEBAB_CASE", // this works
        "domains/**/src/!(__tests__)/**": "KEBAB_CASE", // this works but I want to have a more flexible configuration
      },
    ],
```

**Project structure**
If applicable, add a minimal reproducible project structure generated by the `tree` cmd like the one below.

```sh
.
├── domains
│   ├── sub-domain-a
│   │   ├── src
│   │   │   └── __tests__
│   │   │   │   └── test.ts
│   ├── sub-domain-b
│   │   ├── app
│   │   │   └── __tests__
│   │   │   │   └── test.js
│   ├── sub-domain-c
│   │   ├── feature-a
│   │   │   ├── src
│   │   │   │   └── __tests__
│   │   │   │   │   └── test.js
├── libs
├── scripts
├── package-lock.json
├── package.json
└── .eslintrc.base.json
```

**Desktop:**
 - OS: macOS Sonoma

**Comment by dukeluo** [comment]
@saulo-okada-zs monorepo has more context, could you share a minimal reproducible monorepo project on github so I can work on this?

**Comment by saulo-okada-zs** [comment]
Hey @dukeluo!
Thank you for your fast response.
I can try to create something for you.

Meanwhile, here is some info about our monorepo:
- we are using Lerna
- we have our .eslintrc.base.json and tsconfig.base.json at the root of the project
- Inside each of the sub-domains folders, we have a .eslint.json that is extending our base configuration
- Inside each of the sub-domains folders, we also have a tsconfig.json that is extending our base configuration

I've been trying many different configurations since yesterday.

What I've found was that If I add:
```
    "check-file/folder-naming-convention": [
      "error",
      {
        "domains/**/!(__tests__)/**": "KEBAB_CASE",
      },
```
In the sub-domain .eslintrc.json file, it works as expected.
Adding the same rule to the root .eslintrc.base.json doesn't work as expected.
But, preferably, I would like to have this rule in our base configuration to not replicate the same rule to all my sub-domains

**Comment by saulo-okada-zs** [comment]
I was able to workaround this issue

**Comment by mrbrentkelly** [comment]
I'm experiencing this behavior as well (so might be worth re-opening this issue). What I'm noticing is if I want to exclude the `__tests__` directory at any location in my application directory tree via `**/!(__tests__)/*`, the plugin doesn't work correctly. It will still show linting errors for nested `__tests__` directories.

I've been able to work around it by moving this rule to the `overrides` eslint configuration and excluding `__tests__` in the `files` property...

```json
"overrides": [
  {
    "plugins": ["check-file"],
    "files": ["src/**/!(__tests__)/*"],
    "rules": {
      "check-file/folder-naming-convention": ["error", { 
        "**/*": "KEBAB_CASE" 
      }]
    }
  },
```

**Comment by JacquesBonet3** [comment]
You have to write like that:

 `    'check-file/folder-naming-convention': ['error', { 'src/**/!(__tests__)': 'CAMEL_CASE' }],`
