### ISSUE TITLE
Problem with check-file/folder-naming-convention

### ISSUE THREAD

**Issue by DAMIENDURAND64** [dukeluo/eslint-plugin-check-file#39]
**Describe the bug**
cannot exclude folders named __tests__

**Expected behavior**
'check-file/folder-naming-convention' : I would like to check every name's folder except __tests__

**Project structure**

<img width="320" alt="Capture d’écran 2024-03-04 à 16 19 29" src="https://github.com/dukeluo/eslint-plugin-check-file/assets/113447802/f878d14d-e8cc-48b9-887a-c2e5aacce1e4">

Here is how I am using it : 
'check-file/folder-naming-convention': [
      'error',
      {
        'src/components!(__tests__)/**/': 'CAMEL_CASE',
      },
    ],

**Comment by dukeluo** [comment]
@DAMIENDURAND64 The documentation contains a similar example, which you can refer to: https://github.com/dukeluo/eslint-plugin-check-file/blob/main/docs/rules/folder-naming-convention.md#custom-patterns
