### ISSUE TITLE
Some functions are not compatible with windows

### ISSUE THREAD

**Issue by yscoder** [DukeLuo/eslint-plugin-check-file#4]
https://github.com/DukeLuo/eslint-plugin-check-file/blob/ac5fa6b851f29c5cb2e69dd3665fccd94becf809/lib/utils/filename.js#L11

https://github.com/DukeLuo/eslint-plugin-check-file/blob/ac5fa6b851f29c5cb2e69dd3665fccd94becf809/lib/utils/filename.js#L17

The windows style path is `D:\\path-to\\dir\\filename.js`, is it possible to use `path.basename`, `path.dirname` ?

这两个函数不兼容 windows 系统的路径风格，应该可以用 `path.basename` 和 `path.dirname` 替代

**Comment by DukeLuo** [comment]
Thanks for your feedback. This will be improved in the next version.

**Comment by DukeLuo** [comment]
@yscoder Version 1.2.1 uses `path` module to rewrite these utils, you can try it. Thanks for your reporting.
