### ISSUE TITLE
Can't set the file name convention to be with any prefix 

### ISSUE THREAD

**Issue by YosefSchwartz** [dukeluo/eslint-plugin-check-file#44]
**Describe the bug**
During fixing my project name convention I found this amazing plugin.
I want my hooks will be enforced to start with "use" word, and then keep with "PASCAL_CASE"

**Expected behavior**
A simple way to contact static prefix (not a regex) to the a common type, for example:
```sh
"src/hooks/**.tsx": "use" + "PASCAL_CASE"
```

**Plugin configuration**
not relevant

**Project structure**
If applicable, add a minimal reproducible project structure generated by the `tree` cmd like the one below.

```sh
.
├── package-lock.json
├── package.json
└── src
    └── hooks
        └── useHook.js
```

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by dukeluo** [comment]
@YosefSchwartz You should use the custom glob expression feature in your case. You can do like this:
```json
  "check-file/filename-naming-convention": [
    "error",
    {
      "src/hooks/*.{js,ts}": "use*([A-Z]*([a-z0-9]))",
    },
  ],
```
