### ISSUE TITLE
Character sets not working?

### ISSUE THREAD

**Issue by moui72** [dukeluo/eslint-plugin-check-file#46]
**Describe the bug**

I am trying to create a filename convention that allows something like `1718716204615-memberSurveyAnswerChoices1.ts` but not something like `1718716204615-member-survey-answer-choices1.ts

```
/Users/tyler.peckenpaugh/pager/titan/apps/titan/api/src/drivers/postgres/migrations/1718716204615-memberSurveyAnswerChoices1.ts
  1:1  error  The filename "1718716204615-memberSurveyAnswerChoices1.ts" does not match the "+([0-9])-+([a-zA-Z0-9]).ts" pattern  check-file/filename-naming-convention
```

**Expected behavior**

The filename "1718716204615-memberSurveyAnswerChoices1.ts" should match the "+([0-9])-+([a-zA-Z0-9]).ts" pattern

```
Welcome to Node.js v20.15.0.
Type ".help" for more information.
> const micromatch = require('micromatch');
undefined
> micromatch.isMatch("1718716204615-memberSurveyAnswerChoices1.ts", "+([0-9])-+([a-zA-Z0-9]).ts")
true
> micromatch.isMatch("1718716204615-member-survey-answer-choices1.ts", "+([0-9])-+([a-zA-Z0-9]).ts")
false
> 
```

**Plugin configuration**
Your configuration of this plugin.

```
        "check-file/filename-naming-convention": [
          "error",
          {
            "**/!(migrations)/*.{ts,js}": "CAMEL_CASE",
            "**/migrations/*.{ts,js}": "+([0-9])-+([a-zA-Z0-9]).ts"
          },
          {
            "ignoreMiddleExtensions": true
          }
        ],
        "check-file/folder-naming-convention": [
          "error",
          {
            "src/**": "KEBAB_CASE"
          }
        ]
```

**Project structure**
If applicable, add a minimal reproducible project structure generated by the `tree` cmd like the one below.

```sh
.
├── apps
│   └── titan
│       ├── api
│       │   ├── src
│       │   │   ├── app.module.ts
│       │   │   │   └── postgres
│       │   │   │       ├── migrations
│       │   │   │       │   ├── 1716580425537-blah-blah.ts
└── .eslintrc.json
```

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**

Use nx for project management in a monorepo, so I execute linting with this command:

```
> npx nx run titan-api:lint
```

**Comment by dukeluo** [comment]
Your custom glob expression should be `+([0-9])-+([a-zA-Z0-9])`, not `+([0-9])-+([a-zA-Z0-9]).ts`, it should not include the file extension.
