### ISSUE TITLE
exclusion for parentheses in folder names

### ISSUE THREAD

**Issue by kiwaiko** [dukeluo/eslint-plugin-check-file#48]
i love the KEBAB_CASE linting for files and folders 
but i also like the idea of using parentheses next folders, 
i  was wondering if there is an option to make an exclusion for parentheses or specific folder like (content),
tried many things but it did not work for me..

**Comment by W3journey** [comment]
The [custom Next.js pattern](https://github.com/dukeluo/eslint-plugin-check-file/blob/main/docs/rules/folder-naming-convention.md#nextjs-custom-pattern)  `NEXT_JS_APP_ROUTER_CASE` might help you with this.
