### ISSUE TITLE
windows compatibility

### ISSUE THREAD

**Issue by yscoder** [DukeLuo/eslint-plugin-check-file#5]
The `micromatch.capture` seems to always return unix path style，but `getAllFolders` using `path.sed`. So in windows `getAllFolders` doesn't work.

https://github.com/DukeLuo/eslint-plugin-check-file/blob/b2a6cc422355a673533c2a77922696e288330688/lib/rules/folder-naming-convention.js#L74-L75

**Comment by DukeLuo** [comment]
@yscoder  Thanks for your reporting and PR. 

Converting all kinds of file paths to POSIX style would be a better choice. After that, we can handle the logic in POSIX style.

**Comment by yscoder** [comment]
Nice!

**Comment by DukeLuo** [comment]
@yscoder  Version 1.2.2 enhances support for the Windows, you can try it now.
